### PR TITLE
Unicode-ization begins

### PR DESCRIPTION
**Pull request by Jenny-fa**
When working on my extension for Beaker, I had to add some Unicode string-handling facilities. Since Lingo already contains a few functions that are related to my task (and since Unicode support is something that is not specific to Beaker), I decided Lingo was ultimately a better place for my Unicode routines.

I modified some of Lingo's character classification and numeric conversion functions in lingo/string.hpp, by the way. I hope you don't mind.

### CODE REVIEW

**Comment by Jenny-fa** [comment]
I made some substantial changes to the string and Unicode routines (including a new `lingo::Character_set_converter` class), extended the CMake find modules (FindICONV.cmake now checks for full Unicode support), merged your latest changes, _and_ performed a cursory once-over on your documentation comments. Also I finally mustered the courage to adopt your idiosyncratic indent style and naming conventions.

(BTW translating Autoconf macros to CMake is _exhausting_. I also had to do a bit of testing with GCC to determine precisely how it handled certain character escape sequences and string encodings.)

**Comment by asutton** [comment]
Can you give a brief summary of the changes made?

Andrew Sutton

**Comment by Jenny-fa** [comment]
... Did I not already? :confused:

In summary:
- Added a configuration header. (All source files updated to `#include` the generated config.hpp.)
- Added a new CMake find module (FindICONV.cmake) and modified the existing one for GMP (FindGMP.cmake).
  - cmake/FindGMP.cmake: The C++ interface is now an (optional) package component.
  - cmake/FindICONV.cmake: New find module that checks for a working implementation of the POSIX `iconv()` function. Also checks whether the implementation is the GNU "flavor" of `iconv()` and whether the implementation supports conversion between Unicode encodings.
- Changed the character classification and numeric conversion functions in string.hpp into templates parameterized by character type in order to work with other string encodings and the new `lingo::to_unescaped()` function template. Also refactored the `lingo::get_in_base()` and `lingo::char_to_int()` into the `lingo::is_digit()` and `lingo::digit_value()` functions, and modified `lingo::string_to_int()` so that it handles negative integers, checks whether the integer is within the range of the destination type, and throws exceptions in the event of an error.
- Added files unicode.hpp, unicode.ipp, and unicode.cpp, which
  - Define Unicode string types suitable for the UTF-8, UTF-16, and UTF-32 encoding forms,
  - Defines a `lingo::to_unescaped()` function template for unescaping character escape sequences, and
  - Defines a `lingo::Character_set_converter` class that encapsulates the conversion of strings from one encoding to another. It's inspired by `std::codecvt` and `std::wstring_convert` from the C++ standard library, except that `lingo::Character_set_converter` describes a unidirectional conversion (as opposed to bidirectional), and it's implemented using the POSIX `iconv()` family of functions.
- Added new 'string', 'unicode', and 'character_set_conversion' tests corresponding to the aforementioned additions.
- Added private dependencies on iconv to the 'lingo' library target.
- Corrected various egregious spelling and grammatical errors in documentation comments.

**Comment by Jenny-fa** [comment]
:disappointed:

**Pull request merged**
