### PR TITLE
Minor changes to CMake-generated build system

### PR DESCRIPTION
**Pull request by Jenny-fa**
Look! I wrote this nice and shiny CMake find module for GMP (a dependency that you forgot to document, by the way). And I also fixed `#include` header paths so that they're relative to the 'lingo' directory and so on.

I'm sorry for my OCD.

### CODE REVIEW

**Comment by asutton** [comment]
Why is it a "fix" to change the header files?

Andrew Sutton

**Comment by Jenny-fa** [comment]
> Why is it a "fix" to change the header files?

In case you ever plan to add installation rules for the headers, in which case the `#include` paths should be relative to the headers' install destination, yes?

Of course, since Lingo currently doesn't provide an 'install' target, the point is largely moot. The changes to the headers were mostly for consistency. Disregard them if you like.

**Comment by asutton** [comment]
> In case you ever plan to add installation rules for the headers, in which
> case the #include paths should be relative to the headers' install
> destination, yes?

Quoted includes will search from the current directory before reverting to
the system search path. It's reasonable to do for .hpp, but I think not for
.cpp files since those should only find the include file in the same dir.

> Of course, since Lingo currently doesn't provide an 'install' target, the
> point is largely moot. The changes to the headers were mostly for
> consistency. Disregard them if you like.

I don't want to filter patches. Make a pull just the cmake stuff.

**Comment by Jenny-fa** [comment]
> I don't want to filter patches. Make a pull just the cmake stuff.

Done. All `#include` paths in .cpp files are now double-quoted (again).

**Pull request merged**
